### ISSUE TITLE
Can't load large file

### ISSUE THREAD

**Issue by toniwillberg** [pongasoft/vst-sam-spl-64#1]
Trying to load a large/long WAV causes the plugin to stop responding on Windows 10 with Ableton Live 10 Lite. Works with shorter/smaller files.

My sample WAV is 6:38 minutes / 66.9MB.

Perhaps the plugin should refuse to load too big files, or alternatively it could load only part of the file.

**Comment by ypujante** [comment]
Thank you for reporting. I did try to open a very large file on macOS (80MB) on my primary machine ("old" mac book pro laptop from 2014) and it works fine (albeit a little less responsive when zooming on the waveform).

I tried on a PC with a smaller file (~40MB) and it becomes unresponsive as you describe which seems quite odd. I am not sure why but will investigate

**Comment by ypujante** [comment]
I believe I was able to track down the issue as I have reported in this forum thread https://sdk.steinberg.net/viewtopic.php?f=4&t=829. I think I should have a fix soon.

On another note, I think this issue is clearly surfacing a more serious design issue with the device which is the fact that all the heavy computation (like resampling) is done in the UI thread. It is good because it doesn't block the music part of it but it is bad because it also locks the UI up (potentially). The "proper" way to fix this would be to spawn a thread and allow for cancellation in the UI... but as I found out (see this thread) https://sdk.steinberg.net/viewtopic.php?f=5&t=828 there is no support in the VST3 SDK for such pattern... so need to "roll your own"... which is a non trivial task to do.

**Comment by ypujante** [comment]
I have made some changes to improve the responsiveness when a large file is being loaded. I also added a warning dialog when the file is large (> 20Mb) to back out. I have tried with much larger file than this on Windows 10 and although it take a little time to load (~10s), once it is loaded it seems to be pretty responsive. It is better if the file is the same sample rate than the DAW (which can be forced by going to the Edit tab and selecting Match). Before the changes, the same file would take in the tens of minutes to even load!

You can download 1.4.1 here: https://github.com/pongasoft/vst-sam-spl-64/releases/tag/v1.4.1
